### ISSUE TITLE
Digest fixed_output is not copy

### ISSUE THREAD

**Issue by matklad** [RustCrypto/traits#12]
The following code fails to compile, which makes working with `Digest` generically pretty inconvenient (especially if you want to store digest's output in a data strcuture):

```Rust
/// Trait making `GenericArray` work, marking types to be used as length of an array
pub unsafe trait ArrayLength<T>: Unsigned {
    /// Associated type representing the array type for the number
    type ArrayType;
}
```

The root cause is https://github.com/fizyk20/generic-array/issues/53

Question: couldn't we use `[u8; n]` instead of `GenericArray<u8, N>` for `FixedOutput` output? I imagine something like this might work?

```
trait Array: Copy + Eq + Ord + AsRef[8u] {}
// Impl `Array` for all [u8; N] either generically, or by a macro

trait FixedOutput {
    type Output: Array
}
```

**Comment by matklad** [comment]
Oups, the code snippet is wrong :( 

There's the correct one:

```Rust
fn test_digest<D: Digest>(mut hash: D) {
    let output = hash.fixed_result();
    let copy1 = output;
    let copy2 = output;
}
```

**Comment by newpavlov** [comment]
You can write the following code:
```Rust
pub fn test_digest<D: Digest>(mut hash: D)
    where GenericArray<u8, D::OutputSize>: Copy
{
    ...
}
```

If I am not missing something it should work without much problems. Unfortunately I don't know a way to add such constraint to the trait.

`FixedOutput` solution was proposed earlier, but I don't like it much because it limits flexibility and requires significant rework. Plus I think the current approach will make it easier to migrate to const generics in (I hope, near) future. With const generics I don't think that we'll see `impl <T: Copy, const N> Copy for [T; N] {}`, as it's inefficient to copy around large arrays, so with it you'll have to use the similar constraint.

**Comment by newpavlov** [comment]
I think this issue can be closed, feel free to write here if proposed solution will not work for you.
