### ISSUE TITLE
Should `PublicKey` be `ConditionallySelectable`?

### ISSUE THREAD

**Issue by mxk** [RustCrypto/traits#1227]
`PublicKey::from_encoded_point()` returns a `CtOption`, but it's not possible to perform further constant-time operations on it because `PublicKey` is not `ConditionallySelectable` (but the `AffinePoint` it contains is). Is this intentional or can `PublicKey` also implement `ConditionallySelectable`?

My use case is making sure that the remote public key is both valid and different from the local public key. I don't think converting `CtOption` to `Option` in this case is problematic, but it would be nice if a constant-time implementation was possible.

**Comment by tarcieri** [comment]
`FromEncodedPoint::from_encoded_point` is a trait. There are use cases where an encoded point represents a secret, e.g. ECDH.

`PublicKey` is non-secret by definition. Yes, that trait impl returns `CtOption`, but that's because it's designed for more use cases than just public keys.

If you feel `ConditionallySelectable` on `PublicKey` is needed, please describe an example threat you are attempting to mitigate.

**Comment by mxk** [comment]
I was originally thinking that it might be preferable to have ECDH fail without leaking the underlying reason (invalid public key vs. identical public key), but in retrospect, I can't think of any threat that would create.

Going to close this. Thanks for your reply!
