### ISSUE TITLE
digest: `VariableOutput::MAX_OUTPUT_SIZE` unit of measurement is not specified in docs

### ISSUE THREAD

**Issue by iwiwsb** [RustCrypto/traits#1308]
Same issue with `fn new(output_size: usize) -> Result<Self, InvalidOutputSize>;` and `fn output_size(&self) -> usize;` 

https://github.com/RustCrypto/traits/blob/a7a62e2de9b0f077958405246f553e3ce5c3c26f/digest/src/lib.rs#LL203C1-L214C36

Is it measured in bits or in bytes? It is a little confusing since the hash functions specifications generally states that the output hash length measured in bits. But judging by the `fn finalize_variable(self, out: &mut [u8]) -> Result<(), InvalidBufferSize>;` the output size in measured in bytes. Am I correct?

In my opinion, a clarification about units of measurement is needed in documentation.

**Comment by ok-ryoko** [comment]
Sizes are indeed measured in bytes. We can determine this by inspecting the doc comments for `*SizeUser` traits in [crypto-common]. For example:

```rust
/// Types which process data in blocks.
pub trait BlockSizeUser {
    /// Size of the block in bytes.
    type BlockSize: BlockSizes;

    /// Return block size in bytes.
    #[inline(always)]
    fn block_size() -> usize {
        Self::BlockSize::USIZE
    }
}
```

This is probably so because fundamental types such as `Block`, `Key` and so on build over a [generic array][GenericArray] of `u8` whose size is included in its type.

Given that crypto-common holds low-level traits, I doubt most end users will search it for this information—I myself have been confused about the sizing elsewhere. Thus, I’m in favour of adding sizing information to a more accessible location, such as module-level documentation.

[crypto-common]: https://github.com/RustCrypto/traits/blob/master/crypto-common/src/lib.rs
[GenericArray]: https://fizyk20.github.io/generic-array/generic_array/struct.GenericArray.html
