### ISSUE TITLE
No example of decrypt_blocks_mut

### ISSUE THREAD

**Issue by EvanCarroll** [RustCrypto/traits#1350]
This project is really inaccessible.  There is a method on `cbc` called decrypt_blocks_mut. There is no test of this trait in the `cbc` package. There is no test or documentation of this trait in this package.  How are people supposed to see how this code is to work without a single example of it.

Please document this. It's a five hour project to learn how to write these two lines in python in Rust. 

```
cipher = AES.new(key, AES.MODE_CBC, IV=iv)    
decrypted = cipher.decrypt(encrypted_value)
```

**Comment by newpavlov** [comment]
As I wrote in your other issue, API of our crates relies heavily on generics, so you have to get a good understanding of Rust traits, if you want to properly understand API of our crates. If you want to learn Rust by playing with our crates... I think it will be a fairly ineffective way of learning things. At least, until [the book](https://github.com/RustCrypto/book) will be written.

[Examples](https://docs.rs/cbc/latest/cbc/index.html) in the `cbc` crate docs should be a fine starting point (which are tested btw). In practice, `decrypt_blocks_mut` is rarely used, most users work with padded block modes, thus our examples focus on them. In [`cbc::Decryptor`](https://docs.rs/cbc/latest/cbc/struct.Decryptor.html) docs you can see that it implements the `BlockDecryptMut` trait. By clicking on it you can see all [its methods](https://docs.rs/cipher/0.4.3/cipher/trait.BlockDecryptMut.html), [`decrypt_blocks_mut)`](https://docs.rs/cipher/0.4.3/cipher/trait.BlockDecryptMut.html#method.decrypt_blocks_mut) is one of method with blanket implementation (a common thing for Rust traits) and, assuming you are familiar enough with block modes, it should be obvious how the method works.

We know that our documentation is far from perfect, but currently we have issues with higher priority. We will appreciate documentation improvement PRs (but remember that documentation has to concise enough, for longer introductions we should use the book), but this issue is not actionable enough, so I am inclined to close it.

**Comment by EvanCarroll** [comment]
It's not about "our code relies heavily on generics" its your code is uniquely undocumented and untested. It doesn't speak well of the quality. You make extensive use of GenericArray, something I only see used in this crate, and have no examples or tests on anything that covers generic array. It's easy to use your slice-based API. It's not clear why you break that for other things. Why can I use slices when decoding with a padding,

    .decrypt_padded_mut::<Pkcs7>(&mut buf)

But not when there is no padding,

    .decrypt_blocks_mut(&mut buf).unwrap();

then I get, expected `&mut [GenericArray<u8, UInt<UInt<UInt<..., ...>, ...>, ...>>]`, found `&mut [u8; 256]`

You have 0 examples of GennericArray. it's not clear how to get from a buffer of `&mut [u8; 256]`, which is totally fine in the padded variant to the GenericArray in the unpadded variant. 

And lastly, I don't understand why there is so much hate for users with this project. I challenge you to find one single encryption library in any other language that doesn't show to call decrypt a slice of bytes in the documentation, with or without padding... Even Zig is more approachable and they only have like 3 people using it. https://github.com/ziglang/zig/blob/master/lib/std/crypto/aes.zig#L84

**Comment by EvanCarroll** [comment]
I look forward to the book. I've done whole backend/front end web services in Rust, and usually between examples and tests I can figure it out. This is beyond the limit of what I can figure out with neither.

**Comment by newpavlov** [comment]
>It's not clear why you break that for other things.

We don't break anything. It's a consequence of current state of the Rust language (i.e. lack of features in the stable version of const generics) and our focus on compile-time correctness. When you see `GenericArray<T, N>`, mentally replace it with `[T; N]`. The method effectively expects `&[[u8; 16]]`, but you provide it with `&[u8; 256]`, which is obviously not correct. It's an example of compile-time correctness which we prioritize in our crates.

Yes, converting `&[u8]` into `&[GenericArray<u8, N>]`, unfortunately, is not easy. Currently, we have to rely on `unsafe` code to do it and for const generics arrays [such method](https://doc.rust-lang.org/std/primitive.slice.html#method.array_chunks) is unstable. But methods like `decrypt_blocks_mut` are low level and you probably should simply use `decrypt_padded_mut` with [`NoPadding`](https://docs.rs/block-padding/latest/block_padding/struct.NoPadding.html) instead.

>I don't understand why there is so much hate for users with this project.

It's a very strong accusation done in bad faith. RustCrypto is developed by volunteers without any corporate backing. Our crates have a very large surface area and have to balance various factors such as efficiency, correctness, maintainability. Our approach is much more flexible than most libraries found in other languages, but it introduces a significant amount of complexity. We do not hide it completely, but guide users towards higher-level APIs.

Our assumptions is that if you are not an expert, you will use higher-level APIs are covered in basic doc examples (`decrypt_blocks_mut` is not one of those). Accusing us of hatred towards users just because you found a sharp edge in a lower-level API is... let's say, not productive. Instead of doing it, after doing your initial research, ask advice on sites like [URLO](https://users.rust-lang.org).

**Comment by EvanCarroll** [comment]
```
use aes::cipher::block_padding::NoPadding;
.decrypt_padded_mut::<NoPadding>(mut &buf)` 
```

Brilliant! I mean don't take this the wrong way. We all want things to get better. I have the unique ability to provide value because I'm not a FULL IDIOT, [I've got some experience.](https://stackoverflow.com/users/124486/evan-carroll) I also will read every word I can find before I put my neck on the chopping block to show how complex this is. I also have really rough skin; but, we're not against self-deprecating humor here, right?

This API is god mode. 0% of people will look at [Decryptor struct](https://docs.rs/cbc/latest/cbc/struct.Decryptor.html) and see

* `decrypt_padded_b2b_mut<P>` Decrypt input and unpad it. Returns resulting ciphertext slice. Returns [UnpadError](https://docs.rs/block-padding/0.3.0/block_padding/struct.UnpadError.html) if padding is malformed or if input length is not multiple of Self::BlockSize.
* `decrypt_blocks_b2b_mut` Decrypt blocks in-place.

And think, I wonder if I can provide a secret "NoPadding" implementation to that when there are method calls on the same page, with the same name, that lack "_padded_`. Feel free to close this (or keep it closed) since it is a documentation request. But the problems here aren't that a book is not yet created. **I wouldn't discount that this should be better explained even without a book.**

If you want a review on the book, someone to provide constructive criticism, feel free to send me any working draft as it's created. If you need feedback I'm here.

I still haven't got this working yet, I'm now over 5 hours into it. Still hacking away.

**Comment by EvanCarroll** [comment]
Also I 100% shouldn't have made that accusation of hate on the project. I take it back. That wasn't the intent. It's just this be a lot of head banging.
