### ISSUE TITLE
digest: reduce the number of required methods in `Digest`?

### ISSUE THREAD

**Issue by fjarri** [RustCrypto/traits#1696]
It seems that a number of currently required methods in `Digest` can be expressed via other methods, for example:
- `chain_update` via `update`
- `finalize` via `finalize_into`
- `finalize_reset` via `reset` and `finalize`
- `finalize_into_reset` via `reset` and `finalize_into`
- possibly, `new` via `new_with_prefix` with an empty slice

Is there a reason it's not currently done?

**Comment by newpavlov** [comment]
You mean why those methods don't have blanket impls? It's because those implementations reside in the [blanket impl](https://docs.rs/digest/latest/src/digest/digest.rs.html#57-129) of the trait itself. It uses the underlying traits directly without adding a layer of indirection. We could've used blanket methods implementations, but it's a very minor implementation detail considering that `Digest` should not be directly implemented by user crates.

**Comment by fjarri** [comment]
Ah, I see, that makes sense. I don't think it would hurt adding the blanket impls still, but I don't insist on it. Closing.
