### ISSUE TITLE
elliptic-curve: hash-to-curve support

### ISSUE THREAD

**Issue by kevinlewi** [RustCrypto/traits#481]
It would be nice to have support for a `from_uniform_bytes` functionality for the elliptic curve implementations that performs the hash-to-curve operations described [here](https://tools.ietf.org/html/draft-irtf-cfrg-hash-to-curve-10), preferably the `_SSWU_RO_` variants!

**Comment by burdges** [comment]
I'd expect some churn coming based upon https://mailarchive.ietf.org/arch/msg/cfrg/ZYlKNd4JJiJxNTYSwrY-ZFb4LeI/

**Comment by tarcieri** [comment]
I think we can potentially work on some hash-to-curve traits while the spec is still in flux.

Note that there is a [`FromDigest`](https://docs.rs/elliptic-curve/0.8.4/elliptic_curve/trait.FromDigest.html) trait, however I have some misgivings about it: it's presently used for hash-to-scalar for the purposes of ECDSA, and as much, I've thought about moving it to the `ecdsa` crate for the next release.

All that said, it's general enough it *could* be used to implement hash-to-curve.

**Comment by tarcieri** [comment]
Here's a library that implements `draft-irtf-cfrg-hash-to-curve-11` and provides some traits: https://crates.io/crates/hash2field

It provides an example for using it with `k256`.

cc @mikelodder7

**Comment by mikelodder7** [comment]
I'm also working on crates for the optimized swu map and isogeny map if that helps. The idea is I've implemented hash2curve so many times and in `no-std` settings that the spec hasn't changed much in terms of code over time. Mostly just updating the information.

**Comment by newpavlov** [comment]
Continuation of this discussion: https://github.com/RustCrypto/elliptic-curves/pull/432#issuecomment-920911693

>But I don't get how that works 

`D::OutputSize: IsEqual<U32> + IsEqual<U64>` effectively says "`OutputSize` can be compared against `U32` and `U64`", i.e. it's a constrain on "capability" which this type posses, not equality check itself. Same goes for `Eq<D::OutputSize, U32>: BitOr<Eq<D::OutputSize, U64>>`, it means "we are able to apply OR to the results of equality check".

`typenum` is somewhat counter-intuitive, since you have to explicitly state a lot of "obvious" stuff.

>I need to bound on support for a specific digest size

I am not sure I see a problem (though I can't say I 100% understand your snippet). `SigningKey` is based on `Scalar`, correct? So bounds of the latter will inevitably leak to bounds of the former. Can you explain what constraints you would like to express?

**Comment by tarcieri** [comment]
Looking at this gist again:

https://play.rust-lang.org/?gist=6547bf4c636d51196326fd26aa4bbdee

...it seems pretty problematic that the scalar type is parameterized by a `Digest`. Scalars have nothing to do with digests. In fact the `elliptic-curve` crate does not presently depend on the `digest` crate at all.

> I am not sure I see a problem (though I can't say I 100% understand your snippet). SigningKey is based on Scalar, correct? So bounds of the latter will inevitably leak to bounds of the former. Can you explain what constraints you would like to express?

The main bound I need for ECDSA is this one:

> Scalar<C>: FromDigest<FieldSize<C>>

I want to express that a particular scalar type impls `FromDigest` with a digest output size equal to the size of the curve's scalar field.

**Comment by newpavlov** [comment]
>...it seems pretty problematic that the scalar type is parameterized by a Digest. Scalars have nothing to do with digests, or rather, the relationship is at most a From one. 

This is why I wrote that this trait probably should be implemented by a wrapper. I do agree that it's worth to keep `elliptic-curve` and implementation crates hash-agnostic. It looks a bit strange to go to bother to the level of passing unfinalized hash function and lose the type-level tracking of used hash function immediately afterwards.

>I want to express that a particular scalar type impls FromDigest with a digest output size equal to the size of the curve's scalar field.

Then write this constraint directly as I've done it in the snippet using the `typenum` operators and marker traits?

**Comment by tarcieri** [comment]
I don't understand how to express that, and as a general comment I find those trait bounds extremely hard to read.

**Comment by tarcieri** [comment]
>  It looks a bit strange to bother to the level of passing unfinalized hash function instead of hash value and loose the type-level tracking of used hash function immediately afterwards.

The primary rationale for that is a misuse-resistant API which upholds the requirements of e.g. the Fiat-Shamir heuristic. See:

- https://docs.rs/signature/1.3.1/signature/trait.DigestSigner.html#notes
- https://docs.rs/signature/1.3.1/signature/trait.DigestVerifier.html#notes

**Comment by tarcieri** [comment]
I would consider the hash-to-scalar case mostly addressed by the introduction of a `Reduce` trait in #768. We could perhaps add direct support for computing a `Scalar` from a `Digest`, but otherwise it's a simple composition of the `Reduce`+`Digest` traits.

The larger remaining issue is hashing to elliptic curve points ala `draft-irtf-cfrg-hash-to-curve`. We need to define traits, and then implement those traits in the `k256`/`p256` crates.

Perhaps we could look to something like @mikelodder7's aforementioned [`hash2curve` crate](https://docs.rs/hash2curve/0.1.0/hash2curve/) for inspiration.

**Comment by str4d** [comment]
The `bls12_381` crate has an implementation of the hash-to-curve ID that is both no-std compatible and uses `HashToField` and `HashToCurve` traits: https://github.com/zkcrypto/bls12_381/blob/main/src/hash_to_curve/mod.rs

The impl is currently behind an experimental feature flag, both in case the ID changes, and because we wanted feedback on the trait design. I'd be happy to help uplift (something like) those traits into either `group` or `elliptic-curve`.

**Comment by daxpedda** [comment]
Just linking the current progress so people can chime in on their needs:
- #854
- #855
- #865
- #874
- #876

And the actual implementation on curves:
- RustCrypto/elliptic-curves#495 (outdated)
- RustCrypto/elliptic-curves#503

**Comment by tarcieri** [comment]
I can cut a release, but please keep in mind that once I do all features are stable until the next breaking release.

Are you ready for that? Alternatively we can try to land the PRs to https://github.com/RustCrypto/elliptic-curves first (using a `[patch.crates-io]` directive to pull in `elliptic-curve` via git)

**Comment by daxpedda** [comment]
I didn't actually mean to ask for a release, but it would actually be great. I already tried the API for the projects I'm working on, so as far as I'm concerned the API is fine. I noticed a small thing that could be improved that I will PR for.

> Alternatively we can try to land the PRs to https://github.com/RustCrypto/elliptic-curves first (using a `[patch.crates-io]` directive to pull in `elliptic-curve` via git)

Why? What do you have in mind we would gain from doing that first?

**Comment by tarcieri** [comment]
If you're happy with the API, then I can go ahead and cut a release.

@mikelodder7 are you ok with that?

**Comment by daxpedda** [comment]
See #881. Otherwise I'm good to go.

**Comment by mikelodder7** [comment]
Yes I’m happy with where we’ve landed

**Comment by tarcieri** [comment]
I think we're good to go here now
