### ISSUE TITLE
Key exchange / KEM traits

### ISSUE THREAD

**Issue by jyao1** [RustCrypto/traits#498]
May I know if there is any key_exchange traits defined, or to be defined in the future?

For example, the finite field diffie-hellman ephemeral (FFDHE) or ecliptic curve diffie-hellman ephemeral (ECDHE) - https://github.com/briansmith/ring/blob/main/src/agreement.rs

**Comment by tarcieri** [comment]
The `elliptic-curve` crate has an `ecdh` crate feature/API which supports both static DH and ECDHE:

https://docs.rs/elliptic-curve/latest/elliptic_curve/ecdh/index.html

See the `p256` for concrete usage:

https://docs.rs/p256/latest/p256/ecdh/index.html

We don't presently have any sort of implementation of FFDH.

**Comment by jyao1** [comment]
Thank you very much for the quick response.
I am looking for a way to abstract key_exchange, because the crypto agile requirement for both ECDHE and FFDHE.

There are traits for AEAD/Digest/Signature/MAC. HKDF is discussed in https://github.com/RustCrypto/traits/issues/5
It seems only KeyExchange trait is not there. Is that something this project want to add in the future?

**Comment by tarcieri** [comment]
Sure, it's something we should eventually address

**Comment by tarcieri** [comment]
For various protocols, it may make sense to define [KEM](https://en.wikipedia.org/wiki/Key_encapsulation) traits. Protocols like [HPKE](https://datatracker.ietf.org/doc/draft-irtf-cfrg-hpke/) are defined in terms of KEMs, and it's the API shape being targeted by post-quantum crypto standardization processes.

**Comment by rozbb** [comment]
Hi all, I was thinking about what a set of KEM traits would look like. My starting point was the `signature` traits since they're very similar.

I'd love to have feedback on this initial foray into KEM traits. I suspect the first option is the better one, but it's not as ergonomic as I'd like it to be.

### A note: AuthEncap

First, we need "sender-authenticated key encapsulation", as in HPKE's [`AuthEncap()`](https://cfrg.github.io/draft-irtf-cfrg-hpke/draft-irtf-cfrg-hpke.html#section-4.1), which, in Diffie-Hellman land, involves a static-eph + eph-static key exchange.

One current problem is in generalizability to pq-crypto: I don't think there is any known non-interactive authenticated key exchange for post-quantum primitives. That said, there are plenty of such exchanges for non-pq primitives, with different properties (everything from static-static ECDH up to X3DH with an optional 4th eph-otk exchange).

# KEM API Option 1: Method-centric API

We mimic the structure of the traits found in the `signature` crate. In the same form as `Signature`, we get
```rust
trait EncappedKey: AsRef<[u8]> + Debug + Sized;
```
Next, in the same form as the `Signer<S: Signature>` trait, we get
```rust
trait Encapsulator<EK: EncappedKey> {
    fn try_encap<R: RngCore + CryptoRng>(csprng: &mut R) -> Result<EK, Error>;
}
```
So the way you'd use this is by doing `impl Encapsulator<Blah> for PublicKey` for whatever `PublicKey` is relevant, and then calling `pk.encap(&mut rng)` to encapsulate.

The decapsulator is a little departure, since it requires an associated type:
```rust
trait Decapsulator<EK: EncappedKey> {
    type SharedSecret: AsRef<[u8]> + Sized;

    fn try_decap(encapped_key: &EK) -> Result<Self::SharedSecret, Error>;
}
```
The way you'd use this is `sk.decap(encapped_key)`.

It gets a little messier when we get to the authenticated traits though. Expanding on `Encapsulator` and `Decapsulator`,
```rust
pub trait AuthEncapsulator<EK: EncappedKey> {
    type SenderPrivateKey;

    fn try_auth_encap<R: CryptoRng + RngCore>(
        csprng: &mut R,
        sender_privkey: &Self::SenderPrivateKey,
    ) -> Result<EK, Error>;
}

pub trait AuthDecapsulator<EK: EncappedKey> {
    type SenderPublicKey: AsRef<[u8]> + Debug + Sized;
    type SharedSecret: AsRef<[u8]> + Sized;

    fn try_auth_decap(
        encapped_key: &EK,
        sender_pubkey: &Self::SenderPublicKey,
    ) -> Result<Self::SharedSecret, Error>;
}
```
The way you would use these is `pk.auth_encap(&mut rng, &sk)` and `sk.auth_decap(&ek, &pk)`.
Note that we can't use a parameterized `SharedSecret<D> = GenericArray<...>` type because it would require two different ones: `SharedSecret<D: Decapsulator>` and `AuthSharedSecret<D: AuthDecapsulator>`.

My personal take is that this method syntax is messy, messier than the unary methods from the `signature` traits. Especially having `pk` be the "base object" for an authenticated encapsulation rather than the sender's secret key is odd. That said, I think this is the more viable of the two options.

# KEM API Option 2: Functions not methods

Rather than do the method-based approach above, what about a full API definition
```rust
trait KeyEncapsulation {
    type EncappedKey: AsRef<[u8]> + Debug + Sized;
    type PublicKey: AsRef<[u8]> + Debug + Sized;
    type PrivateKey: AsRef<[u8]> + Sized;
    type SharedSecret: AsRef<[u8]> + Sized;

    fn keygen<R: RngCore + CryptoRng>(csprng: &mut R) -> (Self::PrivateKey, Self::PublicKey);

    fn try_encap<R: RngCore + CryptoRng>(
        csprng: &mut R,
        recip_pubkey: &Self::PublicKey,
    ) -> Result<Self::EncappedKey, Error>;

    fn try_decap(
        encapped_key: &EK
    ) -> Result<Self::SharedSecret, Error>;
}

trait AuthKeyEncapsulation {
    type EncappedKey: AsRef<[u8]> + Debug + Sized;
    type PublicKey: AsRef<[u8]> + Debug + Sized;
    type PrivateKey: AsRef<[u8]> + Sized;
    type SharedSecret: AsRef<[u8]> + Sized;

    fn keygen<R: RngCore + CryptoRng>(csprng: &mut R) -> (Self::PrivateKey, Self::PublicKey);

    fn try_auth_encap<R: RngCore + CryptoRng>(
        csprng: &mut R,
        recip_pubkey: &Self::PublicKey,
        sender_privkey: &Self::PrivateKey,
    ) -> Result<Self::AuthEncappedKey, Error>;

    fn try_auth_decap(
        encapped_key: &EK
        sender_pubkey: &Self::PublicKey,
    ) -> Result<Self::SharedSecret, Error>;
}
```

The immediate problem with this approach is that it's pretty inflexible. For example, if I wanted to implement X3DH as an `AuthKeyEncapsulation` then I'd have to define a `keygen()` method, but what would that even look like? It'd have to generate an identity key, a medium-term key, and at least one one-time key. That really shouldn't all be done in one keygen.

**Comment by tarcieri** [comment]
Interesting suggestions @rozbb. I'd say my initial reaction is I'd generally prefer the method-based approach. A few comments:

> We mimic the structure of the traits found in the signature crate. In the same form as Signature, we get
>
> ```rust
> trait EncappedKey: AsRef<[u8]> + Debug + Sized;
> ```

The `signature` crate was somewhat hampered by a desire to ship a 1.0 and not have a `generic-array` dependency (as `generic-array` is a pre-1.0 crate). 

I suppose there was one other reason why `signature` eschewed a fixed size: ASN.1 DER-encoded signatures are variable length.

I'm curious if it would make sense to use `generic-array` for these types, but that would be dependent on all algorithms being amenable to fixed-sized outputs.

If so, we could eventually migrate to const generics whenever https://github.com/rust-lang/rust/issues/60551 is addressed and stabilized.

**Comment by rozbb** [comment]
You could make `EncappedKey` a `GenericArray` but I'm not sure it's a good fit. At least semantically speaking, an encapped key in HPKE is actually just one or two curve points (two for auth'd), and so I'd probably want to use that as my internal representation in my code.

**Comment by tarcieri** [comment]
#845 specifically addressed the KEM use case.

I think this is probably sufficient to close this issue as KEMs are the preferred interface for key exchange.

There may be some merit in pursuing a Diffie-Hellman abstraction, but currently the only thing in our pantheon of crates that supports Diffie-Hellman is the `elliptic-curve` crate which already provides a generic `ecdh` implementation.

If we ever do add traditional FFDH, we can circle back on some sort of Diffie-Hellman abstraction.
